<template>
  <v-form-render :form-json="formJson" :form-data="formData" :option-data="optionData" ref="vFormRef"> </v-form-render>
  <el-button type="primary" @click="submitForm">Submit</el-button>
</template>

<script setup lang="ts" name="home">
import { ref, reactive } from "vue";
import { ElMessage } from "element-plus";

/* 注意：formJson是指表单设计器导出的json，此处演示的formJson只是一个空白表单json！！ */
const formJson = reactive({
  widgetList: [
    {
      key: 16615,
      type: "card",
      category: "container",
      icon: "card",
      widgetList: [
        {
          key: 41819,
          type: "grid",
          alias: "column-3-grid",
          category: "container",
          icon: "column-3-grid",
          cols: [
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "表单主题",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "表单主题",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: [],
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input107114"
                }
              ],
              options: {
                name: "gridCol38794",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 16,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "grid-col-38794"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "表单编号",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "表单编号",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: "",
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input77557"
                }
              ],
              options: {
                name: "gridCol110763",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "grid-col-110763"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请人姓名",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请人姓名",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: [],
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input57807"
                }
              ],
              options: {
                name: "gridCol42380",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: []
              },
              id: "grid-col-42380"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请人工号",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请人工号",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: "",
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input48156"
                }
              ],
              options: {
                name: "gridcol105773",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "gridcol105773"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请人邮箱",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请人邮箱",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: "",
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input39448"
                }
              ],
              options: {
                name: "gridcol76574",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "gridcol76574"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请人部门",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请人部门",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: "",
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input71139"
                }
              ],
              options: {
                name: "gridcol37214",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "gridcol37214"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请人科室",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请人科室",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: [],
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input105451"
                }
              ],
              options: {
                name: "gridcol87036",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: []
              },
              id: "gridcol87036"
            },
            {
              type: "grid-col",
              category: "container",
              icon: "grid-col",
              internal: true,
              widgetList: [
                {
                  key: 17375,
                  type: "input",
                  alias: "",
                  icon: "text-field",
                  formItemFlag: true,
                  options: {
                    name: "申请日期",
                    keyNameEnabled: false,
                    keyName: "",
                    label: "申请日期",
                    labelAlign: "",
                    type: "text",
                    defaultValue: "",
                    placeholder: "",
                    columnWidth: "200px",
                    size: "",
                    labelWidth: null,
                    labelHidden: false,
                    labelWrap: false,
                    readonly: false,
                    disabled: false,
                    hidden: false,
                    clearable: true,
                    showPassword: false,
                    required: false,
                    requiredHint: "",
                    validation: "",
                    validationHint: "",
                    customClass: "",
                    labelIconClass: null,
                    labelIconPosition: "rear",
                    labelTooltip: null,
                    minLength: null,
                    maxLength: null,
                    showWordLimit: false,
                    prefixIcon: "",
                    suffixIcon: "",
                    appendButton: false,
                    appendButtonDisabled: false,
                    buttonIcon: "custom-search",
                    appendText: false,
                    textForAppend: "",
                    onCreated: "",
                    onMounted: "",
                    onInput: "",
                    onChange: "",
                    onFocus: "",
                    onBlur: "",
                    onValidate: "",
                    onAppendButtonClick: ""
                  },
                  id: "input46985"
                }
              ],
              options: {
                name: "gridcol62068",
                hidden: false,
                span: 8,
                offset: 0,
                push: 0,
                pull: 0,
                responsive: true,
                md: 8,
                sm: 12,
                xs: 24,
                customClass: ""
              },
              id: "gridcol62068"
            }
          ],
          options: {
            name: "grid38655",
            hidden: false,
            gutter: 12,
            colHeight: null,
            customClass: ""
          },
          id: "grid38655"
        }
      ],
      options: {
        name: "申请人信息",
        label: "申请人信息",
        hidden: false,
        headerHidden: false,
        folded: false,
        showFold: true,
        cardWidth: "100%",
        shadow: "never",
        customClass: []
      },
      id: "card61622"
    }
  ],
  formConfig: {
    modelName: "formData",
    refName: "vForm",
    rulesName: "rules",
    labelWidth: 80,
    labelPosition: "left",
    h5LabelTop: false,
    gridResponsive: true,
    size: "",
    labelAlign: "label-left-align",
    cssCode: "",
    customClass: [],
    functions: "",
    layoutType: "PC",
    jsonVersion: 3,
    dataSources: [],
    onFormCreated: "",
    onFormMounted: "",
    onFormDataChange: "",
    onFormValidate: ""
  }
});
const formData = reactive({});
const optionData = reactive({});
const vFormRef = ref(null);

const submitForm = () => {
  vFormRef.value
    .getFormData()
    .then(formData => {
      // Form Validation OK
      alert(JSON.stringify(formData));
    })
    .catch(error => {
      // Form Validation failed
      ElMessage.error(error);
    });
};
</script>

<style scoped lang="scss">
@import "./index.scss";
</style>
